// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzdbzbrertacbynkilqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZGJ6YnJlcnRhY2J5bmtpbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODkyMTMsImV4cCI6MjA2NDI2NTIxM30.CUEwbcXQpedKC29Doz1WQxDQh6-Tz9it4PkhO7kbX4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);